<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.example.categoryservice.domain.model.CategoryTest" tests="15" skipped="0" failures="3" errors="0" timestamp="2025-09-15T14:35:35" hostname="Sunhong-Mac-mini.local" time="0.022">
  <properties/>
  <testcase name="같은_ID를_가진_카테고리는_동등하다()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.0"/>
  <testcase name="다른_ID를_가진_카테고리는_동등하지_않다()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.0"/>
  <testcase name="빈_이름으로_카테고리_생성시_예외발생()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.0"/>
  <testcase name="카테고리를_루트로_변경()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.001"/>
  <testcase name="너무_긴_이름으로_카테고리_생성시_예외발생()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.0"/>
  <testcase name="null_이름으로_카테고리_생성시_예외발생()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.0"/>
  <testcase name="카테고리_문자열_표현_확인()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.002"/>
  <testcase name="너무_긴_설명으로_카테고리_생성시_예외발생()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.002">
    <failure message="java.lang.AssertionError: &#10;Expecting code to raise a throwable." type="java.lang.AssertionError">java.lang.AssertionError: 
Expecting code to raise a throwable.
	at com.example.categoryservice.domain.model.CategoryTest.너무_긴_설명으로_카테고리_생성시_예외발생(CategoryTest.java:215)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</failure>
  </testcase>
  <testcase name="정상적인_하위_카테고리_생성()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.001"/>
  <testcase name="카테고리_정보_업데이트()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.0"/>
  <testcase name="자기_자신을_부모로_설정시_예외발생()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.0"/>
  <testcase name="카테고리_부모_변경()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.0"/>
  <testcase name="카테고리_생성시_생성일시_자동_설정()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.001">
    <failure message="java.lang.AssertionError: &#10;Expecting actual not to be null" type="java.lang.AssertionError">java.lang.AssertionError: 
Expecting actual not to be null
	at com.example.categoryservice.domain.model.CategoryTest.카테고리_생성시_생성일시_자동_설정(CategoryTest.java:187)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</failure>
  </testcase>
  <testcase name="카테고리_업데이트시_수정일시_변경()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.013">
    <failure message="java.lang.IllegalArgumentException: The LocalDateTime to compare actual with should not be null" type="java.lang.IllegalArgumentException">java.lang.IllegalArgumentException: The LocalDateTime to compare actual with should not be null
	at org.assertj.core.util.Preconditions.checkArgument(Preconditions.java:131)
	at org.assertj.core.api.AbstractLocalDateTimeAssert.assertLocalDateTimeParameterIsNotNull(AbstractLocalDateTimeAssert.java:464)
	at org.assertj.core.api.AbstractLocalDateTimeAssert.isAfter(AbstractLocalDateTimeAssert.java:224)
	at com.example.categoryservice.domain.model.CategoryTest.카테고리_업데이트시_수정일시_변경(CategoryTest.java:205)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</failure>
  </testcase>
  <testcase name="정상적인_루트_카테고리_생성()" classname="com.example.categoryservice.domain.model.CategoryTest" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
